name: simplydrug
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - jupyter
  - scikit-learn
  - numpy
  - pandas
  - rdkit=2019.09.3
  - scipy
  - matplotlib
  - seaborn=0.10.0
  - pip:
    - nbdev
    - pubchempy
    - python-pptx
    - wget
    - xlrd
