name: simplydrug
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - rdkit=2019.09.3
  - scipy
  - seaborn
  - pip:
    - matplotlib
    - nbdev
    - pubchempy
    - python-pptx
    - scikit-learn
    - sklearn
    - wget
    - xlrd
